title: めぐるめマップ
description: 目黒周辺のグルメマップです
data_url: https://docs.google.com/spreadsheets/d/e/2PACX-1vSGORBHQ-rYStYaZl7sTRV2INmTFslf4WkH8n_0JR2GAieD0qxH89q6RzOfX9ZuwP_1ePp0-0lXLSzP/pub?gid=1957425126&single=true&output=csv
form_url:
logo_image_url: https://kai4den.github.io/megourmet_map/megmap.svg
background_image_url: https://kai4den.github.io/megourmet_map/meguro_map.jpg
primary_color: "#01565D"
orderby: distance
